app:
  name: testing-compilers
  labels:
    app: testing-compilers
    app.kubernetes.io/part-of: testing-compilers
    app.kubernetes.io/instance: testing-compilers
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    app.openshift.io/runtime: SpringBoot
    app.kubernetes.io/component: testing-compilers
    app.kubernetes.io/name: testing-compilers
    app.openshift.io/runtime-version: "4.0.2"

image:
  name: default-route-openshift-image-registry.apps.icta.sandbox2670.opentlc.com/icta-deployments/testing-compilers
  tag: 0.0.1-SNAPSHOT
  stableTag: 0.0.1-SNAPSHOT

deploy:
  enabledServerless: true
  replicas: 0

  serverless:
    percent: 100
    latestRevision: true
    timeoutSeconds: 300
    enableServiceLinks: false

  ports:
  - name: h2c
    port: 8080
    targetPort: 8080
    protocol: TCP

  resources: {}
    
  livenessProbe:
    enabled: true
    config:
      httpGet:
        path: /q/health/live
        port: 8080
      initialDelaySeconds: 40
      periodSeconds: 5
      failureThreshold: 1

  readinessProbe:
    enabled: true
    config:
      httpGet:
        path: /q/health/ready
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 1

  env:
  - name: TZ
    value: America/Bogota
                              
  envFrom:
    enabled: false

  applicationProperties:
    enabled: false
    # mountPath: /deployments/config/
    # properties: |-
    #   ## Properties go here

  # volumes:
  #   - name: kafka-cert-volume
  #     secret:
  #       secretName: kafka-jks-secret
  #       items:
  #         - key: jks-file
  #           path: client.truststore.jks
  #   - name: config-volume
  #     secret:
  #       secretName: kafka-consumer
  #       items:
  #         - key: entidades
  #           path: entidades.json

  # volumeMounts:
  #     - name: kafka-cert-volume
  #       mountPath: /etc/ssl/certs/kafka
  #       readOnly: true 
  #     - name: config-volume
  #       mountPath: /etc/config/entidades
  #       readOnly: true 

  serviceType: ClusterIP
  
  # imagePullSecrets:
  #   name: auth-quay-acm

  route:
    enabled: true
    targetPort: http
    tls:
      enabled: false
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      key:
      caCertificate:
      certificate:
      destinationCACertificate:

  secret:
  - enabled: false

autoscaling:
  target: 40
  metric: rps
  autoscaling.knative.dev/min-scale: '1' 
# autoscaling:
#   enabled: false
#   minReplicas: 0
#   maxReplicas: 1
#   targetCPUUtilizationPercentage: 80